name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mrorbitman/subsyncarr
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/tags/{0}', github.event.repository.default_branch) }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## Docker Images

            Pull the image using:
            ```bash
            docker pull mrorbitman/subsyncarr:${{ github.ref_name }}
            # or
            docker pull mrorbitman/subsyncarr:latest
            ```

            Example docker-compose.yaml:

            ```
            name: subsyncarr

            services:
              subsyncarr:
                image: mrorbitman/subsyncarr:latest
                container_name: subsyncarr
                volumes:
                  # Any path configured with SCAN_PATHS env var must be mounted
                  # If no scan paths are specified, it defaults to scan `/scan_dir` like example below.
                  # - ${MEDIA_PATH:-/path/to/your/media}:/scan_dir
                  - /path/to/movies:/movies
                  - /path/to/tv:/tv
                  - /path/to/anime:/anime
                restart: unless-stopped
                environment:
                  - TZ=${TZ:-UTC}
                  - CRON_SCHEDULE=0 0 * * *  # Runs every day at midnight by default
                  - SCAN_PATHS=/movies,/tv,/anime # Remember to mount these as volumes. Must begin with /. Default valus is `/scan_dir`
                  - EXCLUDE_PATHS=/movies/temp,/tv/downloads # Exclude certain sub-directories from the scan
                  - MAX_CONCURRENT_SYNC_TASKS=1
                  - INCLUDE_ENGINES=ffsubsync,autosubsync # If not set, all engines are used by default
            ```

            Docker Hub URL: https://hub.docker.com/r/mrorbitman/subsyncarr/tags
          draft: false
          prerelease: false
